apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mymongodb
  name: mymongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mymongodb
status:
  loadBalancer: {}
