apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mymongodb
spec:
  selector:
    matchLabels:
      app: mymongodb
  serviceName: mymongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mymongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mymongodb
        image: alvarorm/mymongodb:latest
        ports:
        - containerPort: 27017
          name: mymongodb
