apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: restaurantapp
  name: restaurantapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: restaurantapp
status:
  loadBalancer: {}

